DROP TABLE IF EXISTS demand_order;
CREATE TABLE demand_order
(
	id VARCHAR(32) NOT NULL COMMENT 'ID',
	customer VARCHAR(32) NULL DEFAULT NULL COMMENT 'customer',
	product VARCHAR(32) NULL DEFAULT NULL COMMENT 'product',
	date Date NULL DEFAULT NULL COMMENT 'date',
	quantity INT(12) NULL DEFAULT NULL COMMENT 'quantity',
	upload_id VARCHAR(50) NULL DEFAULT NULL COMMENT 'uploadId',
	PRIMARY KEY (id)
);
DROP TABLE IF EXISTS supply;
CREATE TABLE supply
(
	id VARCHAR(32) NOT NULL COMMENT 'ID',
	site VARCHAR(32) NULL DEFAULT NULL COMMENT 'site',
	product VARCHAR(32) NULL DEFAULT NULL COMMENT 'product',
	date Date NULL DEFAULT NULL COMMENT 'date',
	quantity INT(12) NULL DEFAULT NULL COMMENT 'quantity',
	upload_id VARCHAR(50) NULL DEFAULT NULL COMMENT 'uploadId',
	PRIMARY KEY (id)
);
DROP TABLE IF EXISTS sourcing_rule;
CREATE TABLE sourcing_rule
(
	id VARCHAR(32) NOT NULL COMMENT 'ID',
	site VARCHAR(32) NULL DEFAULT NULL COMMENT 'site',
	customer VARCHAR(32) NULL DEFAULT NULL COMMENT 'customer',
	product VARCHAR(32) NULL DEFAULT NULL COMMENT 'product',
	upload_id VARCHAR(50) NULL DEFAULT NULL COMMENT 'uploadId',
	PRIMARY KEY (id)
);
DROP TABLE IF EXISTS order_execution_plan;
CREATE TABLE order_execution_plan
(
	id VARCHAR(32) NOT NULL COMMENT 'ID',
	site VARCHAR(32) NULL DEFAULT NULL COMMENT 'site',
	customer VARCHAR(32) NULL DEFAULT NULL COMMENT 'customer',
	product VARCHAR(32) NULL DEFAULT NULL COMMENT 'product',
	execute_date Date NULL DEFAULT NULL COMMENT 'executeDate',
	quantity INT(12) NULL DEFAULT NULL COMMENT 'quantity',
	upload_id VARCHAR(50) NULL DEFAULT NULL COMMENT 'uploadId',
	PRIMARY KEY (id)
);